[package]
name = "rust-fhe"
version = "0.1.0"
edition = "2021"

[dependencies]
tfhe = { version = "*", features = ["boolean", "shortint", "integer"] }
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"

[[bin]]
name = "fhe"
path = "src/main.rs"
