/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IConfig,
  IConfigInterface,
} from "../../../contracts/FHEIntentsERC4626Vault.sol/IConfig";

const _abi = [
  {
    inputs: [],
    name: "getFhePublicCID",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "vault",
        type: "address",
      },
    ],
    name: "isWhitelisted",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IConfig__factory {
  static readonly abi = _abi;
  static createInterface(): IConfigInterface {
    return new Interface(_abi) as IConfigInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IConfig {
    return new Contract(address, _abi, runner) as unknown as IConfig;
  }
}
