coverage:
  status:
    project:
      default:
        target: 95%
        threshold: 0%
        branches:
          - main
        informational: false
    patch:
      default:
        target: 97%
        threshold: 0%
        informational: false

  ignore:
    - "test/**"
    - "**/mocks/**"
    - "**/*.t.sol"
    - "artifacts/**"
    - "protocol-ops/**"
    - "audits/**"
    - "*.config.ts"
    - "*.md"
    - "assets/**"
